export const ACCEPTABLE_BOUNDARY_PATH_TYPES = {
    TOP_LEFT_CORNER : ['RIGHT_BOTTOM'],
    TOP_RIGHT_CORNER : ['LEFT_BOTTOM'],
    TOP : ['HORIZONTAL_STRAIGHT','HORIZONTAL_BOTTOM', 'RIGHT_BOTTOM',  'LEFT_BOTTOM'],
    BOTTOM_LEFT_CORNER : ['RIGHT_TOP'],
    BOTTOM_RIGHT_CORNER : ['LEFT_TOP'],
    BOTTOM : ['HORIZONTAL_STRAIGHT', 'HORIZONTAL_TOP', 'RIGHT_TOP', 'LEFT_TOP'],
    LEFT : ['VERTICAL_STRAIGHT', 'VERTICAL_RIGHT', 'RIGHT_BOTTOM', 'RIGHT_TOP'],
    RIGHT : ['VERTICAL_STRAIGHT', 'VERTICAL_LEFT', 'LEFT_BOTTOM', 'LEFT_TOP'],
    CENTER : ['RIGHT_BOTTOM', 'LEFT_BOTTOM', 'HORIZONTAL_STRAIGHT', 'HORIZONTAL_BOTTOM', 'HORIZONTAL_TOP', 'VERTICAL_STRAIGHT',
                'VERTICAL_RIGHT', 'RIGHT_TOP','LEFT_TOP', 'CROSS' ]
}

