export const ACCEPTABLE_BOUNDARY_PATH_TYPES = {
    TOP_LEFT_CORNER : ['RIGHT_BOTTOM'],
    TOP_RIGHT_CORNER : ['LEFT_BOTTOM'],
    TOP : ['HORIZONTAL_STRAIGHT','HORIZONTAL_BOTTOM', 'RIGHT_BOTTOM',  'LEFT_BOTTOM'],
    BOTTOM_LEFT_CORNER : ['RIGHT_TOP'],
    BOTTOM_RIGHT_CORNER : ['LEFT_TOP'],
    BOTTOM : ['HORIZONTAL_STRAIGHT', 'HORIZONTAL_TOP', 'RIGHT_TOP', 'LEFT_TOP'],
    LEFT : ['VERTICAL_STRAIGHT', 'VERTICAL_RIGHT', 'RIGHT_BOTTOM', 'RIGHT_TOP'],
    RIGHT : ['VERTICAL_STRAIGHT', 'VERTICAL_LEFT', 'LEFT_BOTTOM', 'LEFT_TOP'],
    CENTER : ['RIGHT_BOTTOM', 'LEFT_BOTTOM', 'HORIZONTAL_STRAIGHT', 'HORIZONTAL_BOTTOM', 'HORIZONTAL_TOP', 'VERTICAL_STRAIGHT',
                'VERTICAL_RIGHT', 'RIGHT_TOP','LEFT_TOP', 'CROSS' ]
}


export const COMPATIBLE_PATHS = {
    HORIZONTAL_STRAIGHT: {
        TOP: [],
        BOTTOM: [],
        LEFT: ['HORIZONTAL_STRAIGHT', 'HORIZONTAL_BOTTOM', 'HORIZONTAL_TOP', 'VERTICAL_RIGHT', 'RIGHT_BOTTOM', 'RIGHT_TOP', 'CROSS'],
        RIGHT: ['HORIZONTAL_STRAIGHT', 'HORIZONTAL_BOTTOM', 'HORIZONTAL_TOP', 'VERTICAL_LEFT', 'LEFT_BOTTOM', 'LEFT_TOP', 'CROSS']
    },
    VERTICAL_STRAIGHT: {
        TOP: ['VERTICAL_STRAIGHT', 'VERTICAL_RIGHT', 'VERTICAL_LEFT', 'RIGHT_BOTTOM', 'LEFT_BOTTOM', 'CROSS', 'HORIZONTAL_BOTTOM'],
        BOTTOM: ['VERTICAL_STRAIGHT', 'VERTICAL_RIGHT', 'VERTICAL_LEFT', 'RIGHT_TOP', 'LEFT_TOP', 'CROSS', 'HORIZONTAL_TOP'],
        LEFT:[],
        RIGHT: [] 
    },
    CROSS: {
        TOP:['VERTICAL_STRAIGHT', 'VERTICAL_RIGHT', 'VERTICAL_LEFT', 'RIGHT_BOTTOM', 'LEFT_BOTTOM', 'CROSS', 'HORIZONTAL_BOTTOM'],
        BOTTOM: ['VERTICAL_STRAIGHT', 'VERTICAL_RIGHT', 'VERTICAL_LEFT', 'RIGHT_TOP', 'LEFT_TOP', 'CROSS', 'HORIZONTAL_TOP'],
        LEFT:['HORIZONTAL_STRAIGHT', 'HORIZONTAL_BOTTOM', 'HORIZONTAL_TOP', 'VERTICAL_RIGHT', 'RIGHT_BOTTOM', 'RIGHT_TOP', 'CROSS'],
        RIGHT: ['HORIZONTAL_STRAIGHT', 'HORIZONTAL_BOTTOM', 'HORIZONTAL_TOP', 'VERTICAL_LEFT', 'LEFT_BOTTOM', 'LEFT_TOP', 'CROSS']
    },
    HORIZONTAL_TOP: {
        TOP:['VERTICAL_STRAIGHT', 'VERTICAL_RIGHT', 'VERTICAL_LEFT', 'RIGHT_BOTTOM', 'LEFT_BOTTOM', 'CROSS', 'HORIZONTAL_BOTTOM'],
        BOTTOM: [],
        LEFT: ['HORIZONTAL_STRAIGHT', 'HORIZONTAL_BOTTOM', 'HORIZONTAL_TOP', 'VERTICAL_RIGHT', 'RIGHT_BOTTOM', 'RIGHT_TOP', 'CROSS'],
        RIGHT: ['HORIZONTAL_STRAIGHT', 'HORIZONTAL_BOTTOM', 'HORIZONTAL_TOP', 'VERTICAL_LEFT', 'LEFT_BOTTOM', 'LEFT_TOP', 'CROSS']
    }, 
    HORIZONTAL_BOTTOM: {
        TOP: [],
        BOTTOM: ['VERTICAL_STRAIGHT', 'VERTICAL_RIGHT', 'VERTICAL_LEFT', 'RIGHT_TOP', 'LEFT_TOP', 'CROSS', 'HORIZONTAL_TOP'],
        LEFT: ['HORIZONTAL_STRAIGHT', 'HORIZONTAL_BOTTOM', 'HORIZONTAL_TOP', 'VERTICAL_RIGHT', 'RIGHT_BOTTOM', 'RIGHT_TOP', 'CROSS'],
        RIGHT: ['HORIZONTAL_STRAIGHT', 'HORIZONTAL_BOTTOM', 'HORIZONTAL_TOP', 'VERTICAL_LEFT', 'LEFT_BOTTOM', 'LEFT_TOP', 'CROSS']
    },
    VERTICAL_RIGHT:{
        TOP:['VERTICAL_STRAIGHT', 'VERTICAL_RIGHT', 'VERTICAL_LEFT', 'RIGHT_BOTTOM', 'LEFT_BOTTOM', 'CROSS', 'HORIZONTAL_TOP'],
        BOTTOM: ['VERTICAL_STRAIGHT', 'VERTICAL_RIGHT', 'VERTICAL_LEFT', 'RIGHT_TOP', 'LEFT_TOP', 'CROSS', 'HORIZONTAL_TOP'],
        LEFT:[],
        RIGHT: ['HORIZONTAL_STRAIGHT', 'HORIZONTAL_BOTTOM', 'HORIZONTAL_TOP', 'VERTICAL_LEFT', 'LEFT_BOTTOM', 'LEFT_TOP', 'CROSS']
    },
    VERTICAL_LEFT:{
        TOP:['VERTICAL_STRAIGHT', 'VERTICAL_RIGHT', 'VERTICAL_LEFT', 'RIGHT_BOTTOM', 'LEFT_BOTTOM', 'CROSS', 'HORIZONTAL_TOP'],
        BOTTOM: ['VERTICAL_STRAIGHT', 'VERTICAL_RIGHT', 'VERTICAL_LEFT', 'RIGHT_TOP', 'LEFT_TOP', 'CROSS', 'HORIZONTAL_TOP'],
        LEFT:['HORIZONTAL_STRAIGHT', 'HORIZONTAL_BOTTOM', 'HORIZONTAL_TOP', 'VERTICAL_RIGHT', 'RIGHT_BOTTOM', 'RIGHT_TOP', 'CROSS'],
        RIGHT: []
    }, 
    RIGHT_BOTTOM: {
        TOP:[],
        BOTTOM: ['VERTICAL_STRAIGHT', 'VERTICAL_RIGHT', 'VERTICAL_LEFT', 'RIGHT_TOP', 'LEFT_TOP', 'CROSS', 'HORIZONTAL_TOP'],
        LEFT:[],
        RIGHT: ['HORIZONTAL_STRAIGHT', 'HORIZONTAL_BOTTOM', 'HORIZONTAL_TOP', 'VERTICAL_LEFT', 'LEFT_BOTTOM', 'LEFT_TOP', 'CROSS']
    },
    RIGHT_TOP: {
        TOP: ['VERTICAL_STRAIGHT', 'VERTICAL_RIGHT', 'VERTICAL_LEFT', 'RIGHT_BOTTOM', 'LEFT_BOTTOM', 'CROSS', 'HORIZONTAL_TOP'],
        BOTTOM: [],
        LEFT:[],
        RIGHT: ['HORIZONTAL_STRAIGHT', 'HORIZONTAL_BOTTOM', 'HORIZONTAL_TOP', 'VERTICAL_LEFT', 'LEFT_BOTTOM', 'LEFT_TOP', 'CROSS']
    },
    LEFT_BOTTOM: {
        TOP: [],
        BOTTOM: ['VERTICAL_STRAIGHT', 'VERTICAL_RIGHT', 'VERTICAL_LEFT', 'RIGHT_TOP', 'LEFT_TOP', 'CROSS', 'HORIZONTAL_TOP'],
        LEFT: ['HORIZONTAL_STRAIGHT', 'HORIZONTAL_BOTTOM', 'HORIZONTAL_TOP', 'VERTICAL_RIGHT', 'RIGHT_BOTTOM', 'RIGHT_TOP', 'CROSS'],
        RIGHT: []
    },
    LEFT_TOP: {
        TOP:['VERTICAL_STRAIGHT', 'VERTICAL_RIGHT', 'VERTICAL_LEFT', 'RIGHT_BOTTOM', 'LEFT_BOTTOM', 'CROSS', 'HORIZONTAL_TOP'],
        BOTTOM: [],
        LEFT:['HORIZONTAL_STRAIGHT', 'HORIZONTAL_BOTTOM', 'HORIZONTAL_TOP', 'VERTICAL_RIGHT', 'RIGHT_BOTTOM', 'RIGHT_TOP', 'CROSS'],
        RIGHT: []
    }
}

export const PATH_ORIENTATION = {
    TOP_FACING : ['HORIZONTAL_TOP', 'VERTICAL_STRAIGHT', 'VERTICAL_RIGHT', 'VERTICAL_LEFT', 'RIGHT_TOP', 'LEFT_TOP', 'CROSS'],
    BOTTOM_FACING : ['HORIZONTAL_BOTTOM', 'VERTICAL_STRAIGHT', 'VERTICAL_RIGHT', 'VERTICAL_LEFT', 'RIGHT_BOTTOM', 'LEFT_BOTTOM', 'CROSS'],
    LEFT_FACING : ['HORIZONTAL_TOP', 'HORIZONTAL_BOTTOM', 'HORIZONTAL_STRAIGHT', 'VERTICAL_LEFT', 'LEFT_BOTTOM', 'LEFT_TOP', 'CROSS'],
    RIGHT_FACING : ['HORIZONTAL_TOP', 'HORIZONTAL_BOTTOM', 'HORIZONTAL_STRAIGHT', 'VERTICAL_RIGHT', 'RIGHT_BOTTOM', 'RIGHT_TOP', 'CROSS']
}